# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markymark.fields.MarkdownField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
